DROP TABLE "user" IF EXISTS;

CREATE TABLE "user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_address VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_emailaddress UNIQUE (email_address);